# Generated by Django 4.2.4 on 2024-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_login', models.CharField(max_length=255)),
                ('master_password', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('server', models.CharField(choices=[('Exness-MT5Real', 'Exness-MT5Real'), ('Exness-MT5Real2', 'Exness-MT5Real2'), ('Exness-MT5Real3', 'Exness-MT5Real3'), ('Exness-MT5Real4', 'Exness-MT5Real4'), ('Exness-MT5Real5', 'Exness-MT5Real5'), ('Exness-MT5Real6', 'Exness-MT5Real6'), ('Exness-MT5Real7', 'Exness-MT5Real7'), ('Exness-MT5Real8', 'Exness-MT5Real8'), ('Exness-MT5Real9', 'Exness-MT5Real9'), ('Exness-MT5Real10', 'Exness-MT5Real10'), ('Exness-MT5Real11', 'Exness-MT5Real11'), ('Exness-MT5Real12', 'Exness-MT5Real12'), ('Exness-MT5Real14', 'Exness-MT5Real14'), ('Exness-MT5Real15', 'Exness-MT5Real15'), ('Exness-MT5Real17', 'Exness-MT5Real17'), ('Exness-MT5Real18', 'Exness-MT5Real18'), ('Exness-MT5Real19', 'Exness-MT5Real19'), ('Exness-MT5Real20', 'Exness-MT5Real20'), ('Exness-MT5Real21', 'Exness-MT5Real21'), ('Exness-MT5Real22', 'Exness-MT5Real22'), ('Exness-MT5Real23', 'Exness-MT5Real23'), ('Exness-MT5Real24', 'Exness-MT5Real24'), ('Exness-MT5Trial', 'Exness-MT5Trial'), ('Exness-MT5Trial2', 'Exness-MT5Trial2'), ('Exness-MT5Trial3', 'Exness-MT5Trial3'), ('Exness-MT5Trial4', 'Exness-MT5Trial4'), ('Exness-MT5Trial5', 'Exness-MT5Trial5'), ('Exness-MT5Trial6', 'Exness-MT5Trial6'), ('Exness-MT5Trial7', 'Exness-MT5Trial7'), ('Exness-MT5Trial8', 'Exness-MT5Trial8'), ('Exness-MT5Trial9', 'Exness-MT5Trial9'), ('Exness-MT5Trial10', 'Exness-MT5Trial10'), ('Exness-MT5Trial11', 'Exness-MT5Trial11'), ('Exness-MT5Trial12', 'Exness-MT5Trial12')], max_length=255)),
            ],
        ),
    ]
