# Generated by Django 4.2.4 on 2024-08-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlogin',
            name='login',
            field=models.IntegerField(),
        ),
    ]
