# Generated by Django 5.0.7 on 2024-08-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_masterlogin_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlogin',
            name='pin',
        ),
    ]
